'use strict';

const collection = {
  TOP_MAC: 'macos-apps/top-mac-apps/all',
  TOP_FREE_MAC: 'macos-apps/top-free-mac-apps/all',
  TOP_GROSSING_MAC: 'macos-apps/top-grossing-mac-apps/all',
  TOP_PAID_MAC: 'macos-apps/top-paid-mac-apps/all',

  NEW_APPS_IOS: 'ios-apps/new-apps-we-love/all',
  NEW_GAMES_IOS: 'ios-apps/new-games-we-love/all',
  TOP_FREE_IOS: 'ios-apps/top-free/all',
  TOP_FREE_GAMES_IOS: 'ios-apps/top-free/games',
  TOP_FREE_IPAD: 'ios-apps/top-free-ipad/all',
  TOP_GROSSING_IOS: 'ios-apps/top-grossing/all',
  TOP_GROSSING_IPAD: 'ios-apps/top-grossing-ipad/all',
  TOP_PAID_IOS: 'ios-apps/top-paid/all',
  TOP_PAID_GAMES_IOS: 'ios-apps/top-paid/games'
};

const device = {
  IPAD: 'iPadSoftware',
  MAC: 'macSoftware',
  ALL: 'software'
};

const sort = {
  RECENT: 'mostRecent',
  HELPFUL: 'mostHelpful'
};

// From https://rss.itunes.apple.com/
const markets = {
	dz: 'Algeria',
	ao: 'Angola',
	ai: 'Anguilla',
	ag: 'Antigua and Barbuda',
	ar: 'Argentina',
	am: 'Armenia',
	au: 'Australia',
	at: 'Austria',
	az: 'Azerbaijan',
	bs: 'Bahamas',
	bh: 'Bahrain',
	bb: 'Barbados',
	by: 'Belarus',
	be: 'Belgium',
	bz: 'Belize',
	bj: 'Benin',
	bm: 'Bermuda',
	bt: 'Bhutan',
	bo: 'Bolivia',
	bw: 'Botswana',
	br: 'Brazil',
	vg: 'British Virgin Islands',
	bn: 'Brunei Darussalam',
	bg: 'Bulgaria',
	bf: 'Burkina Faso',
	kh: 'Cambodia',
	ca: 'Canada',
	cv: 'Cape Verde',
	ky: 'Cayman Islands',
	td: 'Chad',
	cl: 'Chile',
	cn: 'China',
	co: 'Colombia',
	cg: 'Congo, Republic of the',
	cr: 'Costa Rica',
	hr: 'Croatia',
	cy: 'Cyprus',
	cz: 'Czech Republic',
	dk: 'Denmark',
	dm: 'Dominica',
	do: 'Dominican Republic',
	ec: 'Ecuador',
	eg: 'Egypt',
	sv: 'El Salvador',
	ee: 'Estonia',
	fj: 'Fiji',
	fi: 'Finland',
	fr: 'France',
	gm: 'Gambia',
	de: 'Germany',
	gh: 'Ghana',
	gr: 'Greece',
	gd: 'Grenada',
	gt: 'Guatemala',
	gw: 'Guinea-Bissau',
	gy: 'Guyana',
	hn: 'Honduras',
	hk: 'Hong Kong',
	hu: 'Hungary',
	is: 'Iceland',
	in: 'India',
	id: 'Indonesia',
	ie: 'Ireland',
	il: 'Israel',
	it: 'Italy',
	jm: 'Jamaica',
	jp: 'Japan',
	jo: 'Jordan',
	kz: 'Kazakhstan',
	ke: 'Kenya',
	kr: 'Korea, Republic Of',
	kw: 'Kuwait',
	kg: 'Kyrgyzstan',
	la: 'Lao, People&#39;s Democratic Republic',
	lv: 'Latvia',
	lb: 'Lebanon',
	lr: 'Liberia',
	lt: 'Lithuania',
	lu: 'Luxembourg',
	mo: 'Macau',
	mk: 'Macedonia',
	mg: 'Madagascar',
	mw: 'Malawi',
	my: 'Malaysia',
	ml: 'Mali',
	mt: 'Malta',
	mr: 'Mauritania',
	mu: 'Mauritius',
	mx: 'Mexico',
	fm: 'Micronesia, Federated States of',
	md: 'Moldova',
	mn: 'Mongolia',
	ms: 'Montserrat',
	mz: 'Mozambique',
	na: 'Namibia',
	np: 'Nepal',
	nl: 'Netherlands',
	nz: 'New Zealand',
	ni: 'Nicaragua',
	ne: 'Niger',
	ng: 'Nigeria',
	no: 'Norway',
	om: 'Oman',
	pk: 'Pakistan',
	pw: 'Palau',
	pa: 'Panama',
	pg: 'Papua New Guinea',
	py: 'Paraguay',
	pe: 'Peru',
	ph: 'Philippines',
	pl: 'Poland',
	pt: 'Portugal',
	qa: 'Qatar',
	ro: 'Romania',
	ru: 'Russia',
	st: 'São Tomé and Príncipe',
	sa: 'Saudi Arabia',
	sn: 'Senegal',
	sc: 'Seychelles',
	sl: 'Sierra Leone',
	sg: 'Singapore',
	sk: 'Slovakia',
	si: 'Slovenia',
	sb: 'Solomon Islands',
	za: 'South Africa',
	es: 'Spain',
	lk: 'Sri Lanka',
	kn: 'St. Kitts and Nevis',
	lc: 'St. Lucia',
	vc: 'St. Vincent and The Grenadines',
	sr: 'Suriname',
	sz: 'Swaziland',
	se: 'Sweden',
	ch: 'Switzerland',
	tw: 'Taiwan',
	tj: 'Tajikistan',
	tz: 'Tanzania',
	th: 'Thailand',
	tt: 'Trinidad and Tobago',
	tn: 'Tunisia',
	tr: 'Turkey',
	tm: 'Turkmenistan',
	tc: 'Turks and Caicos',
	ug: 'Uganda',
	ua: 'Ukraine',
	ae: 'United Arab Emirates',
	gb: 'United Kingdom',
	us: 'United States',
	uy: 'Uruguay',
	uz: 'Uzbekistan',
	ve: 'Venezuela',
	vn: 'Vietnam',
	ye: 'Yemen',
	zw: 'Zimbabwe'
};

module.exports = {collection, device, sort, markets};
